ServerEvents.recipes(event => {
	  	function cabinet_counter(out, counter, cabinet) {
  	      event.remove({ output: out }),
  	      event.shaped(out, 
  	        ['AB'],
  	        {
  	          A: counter,
  	          B: cabinet
  	        }
  	      )
  	    }
		event.remove({ output: 'woodworks:oak_chest'}),
		event.remove({ output: 'woodworks:dark_oak_chest'}),
		event.remove({ output: 'woodworks:birch_chest'}),
		event.remove({ output: 'woodworks:jungle_chest'}),
		event.remove({ output: 'woodworks:acacia_chest'}),
		event.remove({ output: 'woodworks:mangrove_chest'}),
		event.remove({ output: 'woodworks:cherry_chest'}),
		event.remove({ output: 'woodworks:crimson_chest'}),
		event.remove({ output: 'woodworks:warped_chest'}),
		event.remove({ output: 'woodworks:spruce_chest'}),
		event.remove({ output: 'woodworks:bamboo_chest'}),
		event.remove({ output: 'woodworks:oak_bookshelf'}),
		event.remove({ output: 'woodworks:dark_oak_bookshelf'}),
		event.remove({ output: 'woodworks:birch_bookshelf'}),
		event.remove({ output: 'woodworks:jungle_bookshelf'}),
		event.remove({ output: 'woodworks:acacia_bookshelf'}),
		event.remove({ output: 'woodworks:mangrove_bookshelf'}),
		event.remove({ output: 'woodworks:cherry_bookshelf'}),
		event.remove({ output: 'woodworks:crimson_bookshelf'}),
		event.remove({ output: 'woodworks:warped_bookshelf'}),
		event.remove({ output: 'woodworks:spruce_bookshelf'}),
		event.remove({ output: 'woodworks:bamboo_bookshelf'}),
		event.remove({ output: 'woodworks:oak_ladder'}),
		event.remove({ output: 'woodworks:dark_oak_ladder'}),
		event.remove({ output: 'woodworks:birch_ladder'}),
		event.remove({ output: 'woodworks:jungle_ladder'}),
		event.remove({ output: 'woodworks:acacia_ladder'}),
		event.remove({ output: 'woodworks:mangrove_ladder'}),
		event.remove({ output: 'woodworks:cherry_ladder'}),
		event.remove({ output: 'woodworks:crimson_ladder'}),
		event.remove({ output: 'woodworks:warped_ladder'}),
		event.remove({ output: 'woodworks:spruce_ladder'}),
		event.remove({ output: 'woodworks:bamboo_ladder'}),
		event.remove({ output: 'everycomp:abnww/regions_unexplored/willow_chest'}),
		event.remove({ output: 'everycomp:abnww/biomemakeover/willow_chest'}),
		event.remove({ output: 'everycomp:abnww/biomemakeover/trapped_willow_chest'}),
		event.remove({ output: 'everycomp:abnww/regions_unexplored/willow_trapped_chest'}),
		event.remove({ output: 'everycomp:abnww/biomemakeover/willow_trapped_chest'}),
		event.remove({ output: 'everycomp:abnww/ars_nouveau/archwood_ladder'}),
		event.remove({ output: 'everycomp:abnww/iceandfire/dreadwood_ladder'}),
		event.remove({ output: 'everycomp:abnww/biomemakeover/blighted_balsa_ladder'}),
		event.remove({ output: 'everycomp:abnww/biomemakeover/willow_ladder'}),
		event.remove({ output: 'everycomp:abnww/biomemakeover/swamp_cypress_ladder'}),
		event.remove({ output: 'everycomp:abnww/biomemakeover/ancient_oak_ladder'}),
		event.remove({ output: 'everycomp:abnww/alexscaves/pewen_ladder'}),
		event.remove({ output: 'everycomp:abnww/alexscaves/thornwood_ladder'}),
		event.remove({ output: 'everycomp:abnww/betterarcheology/rotten_ladder'}),
		event.remove({ output: 'everycomp:abnww/regions_unexplored/alpha_ladder'}),
		event.remove({ output: 'everycomp:abnww/regions_unexplored/baobab_ladder'}),
		event.remove({ output: 'everycomp:abnww/regions_unexplored/blackwood_ladder'}),
		event.remove({ output: 'everycomp:abnww/regions_unexplored/blue_bioshroom_ladder'}),
		event.remove({ output: 'everycomp:abnww/regions_unexplored/brimwood_ladder'}),
		event.remove({ output: 'everycomp:abnww/regions_unexplored/cobalt_ladder'}),
		event.remove({ output: 'everycomp:abnww/regions_unexplored/cypress_ladder'}),
		event.remove({ output: 'everycomp:abnww/regions_unexplored/dead_ladder'}),
		event.remove({ output: 'everycomp:abnww/regions_unexplored/eucalyptus_ladder'}),
		event.remove({ output: 'everycomp:abnww/regions_unexplored/green_bioshroom_ladder'}),
		event.remove({ output: 'everycomp:abnww/regions_unexplored/joshua_ladder'}),
		event.remove({ output: 'everycomp:abnww/regions_unexplored/kapok_ladder'}),
		event.remove({ output: 'everycomp:abnww/regions_unexplored/larch_ladder'}),
		event.remove({ output: 'everycomp:abnww/regions_unexplored/magnolia_ladder'}),
		event.remove({ output: 'everycomp:abnww/regions_unexplored/maple_ladder'}),
		event.remove({ output: 'everycomp:abnww/regions_unexplored/mauve_ladder'}),
		event.remove({ output: 'everycomp:abnww/regions_unexplored/palm_ladder'}),
		event.remove({ output: 'everycomp:abnww/regions_unexplored/pine_ladder'}),
		event.remove({ output: 'everycomp:abnww/regions_unexplored/pink_bioshroom_ladder'}),
		event.remove({ output: 'everycomp:abnww/regions_unexplored/redwood_ladder'}),
		event.remove({ output: 'everycomp:abnww/regions_unexplored/socotra_ladder'}),
		event.remove({ output: 'everycomp:abnww/regions_unexplored/willow_ladder'}),
		event.remove({ output: 'everycomp:abnww/regions_unexplored/yellow_bioshroom_ladder'}),
		event.remove({ output: 'everycomp:q/regions_unexplored/maple_bookshelf'}),
		event.remove({ output: 'v_slab_compat:biomemakeover/reed_thatch_vertical_slab'}),
		event.remove({ output: 'v_slab_compat:upgrade_aquatic/beachgrass_thatch_vertical_slab'}),
		event.remove({ output: 'v_slab_compat:spelunkery/rock_salt_vertical_slab'}),
		event.remove({ output: 'v_slab_compat:spelunkery/polished_rock_salt_vertical_slab'}),
		event.remove({ output: 'v_slab_compat:spelunkery/rock_salt_brick_vertical_slab'}),
		event.remove({ output: 'v_slab_compat:betterend/end_stone_brick_weathered_vertical_slab'}),
		event.remove({ output: 'v_slab_compat:betterend/virid_jadestone_bricks_vertical_slab'}),
		event.remove({ output: 'v_slab_compat:betterend/sulphuric_rock_bricks_vertical_slab'}),
		event.remove({ output: 'v_slab_compat:betterend/end_stone_brick_cracked_vertical_slab'}),
		event.remove({ output: 'v_slab_compat:betterend/azure_jadestone_bricks_vertical_slab'}),
		event.remove({ output: 'v_slab_compat:betterend/umbralith_vertical_slab'}),
		event.remove({ output: 'v_slab_compat:betterend/flavolite_vertical_slab'}),
		event.remove({ output: 'v_slab_compat:betterend/azure_jadestone_vertical_slab'}),
		event.remove({ output: 'v_slab_compat:betterend/sulphuric_rock_vertical_slab'}),
		event.remove({ output: 'v_slab_compat:betterend/lucernia_vertical_slab'}),
		event.remove({ output: 'v_slab_compat:betterend/virid_jadestone_vertical_slab'}),
		event.remove({ output: 'v_slab_compat:betterend/tenanea_vertical_slab'}),
		event.remove({ output: 'v_slab_compat:betterend/umbrella_tree_vertical_slab'}),
		event.remove({ output: 'v_slab_compat:betterend/mossy_glowshroom_vertical_slab'}),
		event.remove({ output: 'v_slab_compat:betterend/pythadendron_vertical_slab'}),
		event.remove({ output: 'v_slab_compat:betterend/violecite_vertical_slab'}),
		event.remove({ output: 'v_slab_compat:betterend/smaragdant_crystal_vertical_slab'}),
		event.remove({ output: 'v_slab_compat:betterend/end_lotus_vertical_slab'}),
		event.remove({ output: 'v_slab_compat:betterend/umbralith_bricks_vertical_slab'}),
		event.remove({ output: 'v_slab_compat:betterend/dragon_tree_vertical_slab'}),
		event.remove({ output: 'v_slab_compat:betterend/lacugrove_vertical_slab'}),
		event.remove({ output: 'v_slab_compat:betterend/helix_tree_vertical_slab'}),
		event.remove({ output: 'v_slab_compat:betterend/sandy_jadestone_vertical_slab'}),
		event.remove({ output: 'v_slab_compat:betterend/violecite_bricks_vertical_slab'}),
		event.remove({ output: 'v_slab_compat:betterend/smaragdant_crystal_bricks_vertical_slab'}),
		event.remove({ output: 'v_slab_compat:betterend/jellyshroom_vertical_slab'}),
		event.remove({ output: 'v_slab_compat:betterend/flavolite_bricks_vertical_slab'}),
		event.remove({ output: 'v_slab_compat:betterend/sandy_jadestone_bricks_vertical_slab'}),
  	    event.remove({ id: 'everycomp:abnww/upgrade_aquatic/river_boards' }),
  	    event.remove({ id: 'everycomp:abnww/upgrade_aquatic/driftwood_boards' }),
   		event.remove({ id: 'woodworks:bamboo_closet' }),
  	    event.remove({ id: 'woodworks:oak_ladder' }),
  	    event.remove({ id: 'woodworks:oak_bookshelf' }),
  	    event.remove({ output: 'everycomp:fd/caverns_and_chasms/azalea_cabinet'}),

		cabinet_counter('everycomp:rd/betterarcheology/rotten_cabinet_counter', 'everycomp:rd/betterarcheology/rotten_counter', 'everycomp:fd/betterarcheology/rotten_cabinet'),
		cabinet_counter('everycomp:rd/forbidden_arcanus/edelwood_cabinet_counter', 'everycomp:rd/forbidden_arcanus/edelwood_counter', 'everycomp:fd/forbidden_arcanus/edelwood_cabinet'),
		cabinet_counter('everycomp:rd/forbidden_arcanus/aurum_cabinet_counter', 'everycomp:rd/forbidden_arcanus/aurum_counter', 'everycomp:fd/forbidden_arcanus/aurum_cabinet'),
		cabinet_counter('everycomp:rd/forbidden_arcanus/fungyss_cabinet_counter', 'everycomp:rd/forbidden_arcanus/fungyss_counter', 'everycomp:fd/forbidden_arcanus/fungyss_cabinet'),
		cabinet_counter('everycomp:rd/regions_unexplored/yellow_bioshroom_cabinet_counter', 'everycomp:rd/regions_unexplored/yellow_bioshroom_counter', 'everycomp:fd/regions_unexplored/yellow_bioshroom_cabinet'),
		cabinet_counter('everycomp:rd/regions_unexplored/socotra_cabinet_counter', 'everycomp:rd/regions_unexplored/socotra_counter', 'everycomp:fd/regions_unexplored/socotra_cabinet'),
		cabinet_counter('everycomp:rd/regions_unexplored/redwood_cabinet_counter', 'everycomp:rd/regions_unexplored/redwood_counter', 'everycomp:fd/regions_unexplored/redwood_cabinet'),
		cabinet_counter('everycomp:rd/regions_unexplored/pink_bioshroom_cabinet_counter', 'everycomp:rd/regions_unexplored/pink_bioshroom_counter', 'everycomp:fd/regions_unexplored/pink_bioshroom_cabinet'),
		cabinet_counter('everycomp:rd/regions_unexplored/pine_cabinet_counter', 'everycomp:rd/regions_unexplored/pine_counter', 'everycomp:fd/regions_unexplored/pine_cabinet'),
		cabinet_counter('everycomp:rd/regions_unexplored/mauve_cabinet_counter', 'everycomp:rd/regions_unexplored/mauve_counter', 'everycomp:fd/regions_unexplored/mauve_cabinet'),
		cabinet_counter('everycomp:rd/regions_unexplored/maple_cabinet_counter', 'everycomp:rd/regions_unexplored/maple_counter', 'everycomp:fd/regions_unexplored/maple_cabinet'),
		cabinet_counter('everycomp:rd/regions_unexplored/magnolia_cabinet_counter', 'everycomp:rd/regions_unexplored/magnolia_counter', 'everycomp:fd/regions_unexplored/magnolia_cabinet'),
		cabinet_counter('everycomp:rd/regions_unexplored/green_bioshroom_cabinet_counter', 'everycomp:rd/regions_unexplored/green_bioshroom_counter', 'everycomp:fd/regions_unexplored/green_bioshroom_cabinet'),
		cabinet_counter('everycomp:rd/regions_unexplored/larch_cabinet_counter', 'everycomp:rd/regions_unexplored/larch_counter', 'everycomp:fd/regions_unexplored/larch_cabinet'),
		cabinet_counter('everycomp:rd/regions_unexplored/joshua_cabinet_counter', 'everycomp:rd/regions_unexplored/joshua_counter', 'everycomp:fd/regions_unexplored/joshua_cabinet'),
		cabinet_counter('everycomp:rd/regions_unexplored/kapok_cabinet_counter', 'everycomp:rd/regions_unexplored/kapok_counter', 'everycomp:fd/regions_unexplored/kapok_cabinet'),
		cabinet_counter('everycomp:rd/regions_unexplored/eucalyptus_cabinet_counter', 'everycomp:rd/regions_unexplored/eucalyptus_counter', 'everycomp:fd/regions_unexplored/eucalyptus_cabinet'),
		cabinet_counter('everycomp:rd/regions_unexplored/dead_cabinet_counter', 'everycomp:rd/regions_unexplored/dead_counter', 'everycomp:fd/regions_unexplored/dead_cabinet'),
		cabinet_counter('everycomp:rd/regions_unexplored/cypress_cabinet_counter', 'everycomp:rd/regions_unexplored/cypress_counter', 'everycomp:fd/regions_unexplored/cypress_cabinet'),
		cabinet_counter('everycomp:rd/regions_unexplored/brimwood_cabinet_counter', 'everycomp:rd/regions_unexplored/brimwood_counter', 'everycomp:fd/regions_unexplored/brimwood_cabinet'),
		cabinet_counter('everycomp:rd/regions_unexplored/blue_bioshroom_cabinet_counter', 'everycomp:rd/regions_unexplored/blue_bioshroom_counter', 'everycomp:fd/regions_unexplored/blue_bioshroom_cabinet'),
		cabinet_counter('everycomp:rd/regions_unexplored/blackwood_cabinet_counter', 'everycomp:rd/regions_unexplored/blackwood_counter', 'everycomp:fd/regions_unexplored/blackwood_cabinet'),
		cabinet_counter('everycomp:rd/regions_unexplored/baobab_cabinet_counter', 'everycomp:rd/regions_unexplored/baobab_counter', 'everycomp:fd/regions_unexplored/baobab_cabinet'),
		cabinet_counter('everycomp:rd/regions_unexplored/cobalt_cabinet_counter', 'everycomp:rd/regions_unexplored/cobalt_counter', 'everycomp:fd/regions_unexplored/cobalt_cabinet'),
		cabinet_counter('everycomp:rd/regions_unexplored/alpha_cabinet_counter', 'everycomp:rd/regions_unexplored/alpha_counter', 'everycomp:fd/regions_unexplored/alpha_cabinet'),
		cabinet_counter('everycomp:rd/born_in_chaos_v1/scorched_cabinet_counter', 'everycomp:rd/born_in_chaos_v1/scorched_counter', 'everycomp:fd/born_in_chaos_v1/scorched_cabinet'),
		cabinet_counter('everycomp:rd/upgrade_aquatic/river_cabinet_counter', 'everycomp:rd/upgrade_aquatic/river_counter', 'abnormals_delight:river_cabinet'),
		cabinet_counter('everycomp:rd/upgrade_aquatic/driftwood_cabinet_counter', 'everycomp:rd/upgrade_aquatic/driftwood_counter', 'abnormals_delight:driftwood_cabinet'),
		cabinet_counter('everycomp:rd/alexscaves/pewen_cabinet_counter', 'everycomp:rd/alexscaves/pewen_counter', 'everycomp:fd/alexscaves/pewen_cabinet'),
		cabinet_counter('everycomp:rd/alexscaves/thornwood_cabinet_counter', 'everycomp:rd/alexscaves/thornwood_counter', 'everycomp:fd/alexscaves/thornwood_cabinet'),
		cabinet_counter('everycomp:rd/biomemakeover/ancient_oak_cabinet_counter', 'everycomp:rd/biomemakeover/ancient_oak_counter', 'everycomp:fd/biomemakeover/ancient_oak_cabinet'),
		cabinet_counter('everycomp:rd/biomemakeover/swamp_cypress_cabinet_counter', 'everycomp:rd/biomemakeover/swamp_cypress_counter', 'everycomp:fd/biomemakeover/swamp_cypress_cabinet'),
		cabinet_counter('everycomp:rd/biomemakeover/blighted_balsa_cabinet_counter', 'everycomp:rd/biomemakeover/blighted_balsa_counter', 'everycomp:fd/biomemakeover/blighted_balsa_cabinet'),
		cabinet_counter('everycomp:rd/hexerei/witch_hazel_cabinet_counter', 'everycomp:rd/hexerei/witch_hazel_counter', 'everycomp:fd/hexerei/witch_hazel_cabinet'),
		cabinet_counter('everycomp:rd/hexerei/willow_cabinet_counter', 'everycomp:rd/hexerei/willow_counter', 'everycomp:fd/hexerei/willow_cabinet'),
		cabinet_counter('everycomp:rd/hexerei/mahogany_cabinet_counter', 'everycomp:rd/hexerei/mahogany_counter', 'everycomp:fd/hexerei/mahogany_cabinet'),
		cabinet_counter('everycomp:rd/quark/blossom_cabinet_counter', 'everycomp:rd/quark/blossom_counter', 'everycomp:fd/quark/blossom_cabinet'),
		cabinet_counter('everycomp:rd/quark/azalea_cabinet_counter', 'everycomp:rd/quark/azalea_counter', 'everycomp:fd/quark/azalea_cabinet'),
		cabinet_counter('everycomp:rd/quark/ancient_cabinet_counter', 'everycomp:rd/quark/ancient_counter', 'everycomp:fd/quark/ancient_cabinet'),
		cabinet_counter('everycomp:rd/ars_nouveau/archwood_cabinet_counter', 'everycomp:rd/ars_nouveau/archwood_counter', 'everycomp:fd/ars_nouveau/archwood_cabinet'),
		cabinet_counter('everycomp:rd/netherexp/claret_cabinet_counter', 'everycomp:rd/netherexp/claret_counter', 'everycomp:fd/netherexp/claret_cabinet'),
		cabinet_counter('everycomp:rd/mynethersdelight/powdery_cabinet_counter', 'everycomp:rd/mynethersdelight/powdery_counter', 'everycomp:fd/mynethersdelight/powdery_cabinet'),
		cabinet_counter('everycomp:rd/betternether/nether_mushroom_cabinet_counter', 'everycomp:rd/betternether/nether_mushroom_counter', 'everycomp:fd/betternether/nether_mushroom_cabinet'),
		cabinet_counter('everycomp:rd/betternether/nether_reed_cabinet_counter', 'everycomp:rd/betternether/nether_reed_counter', 'everycomp:fd/betternether/nether_reed_cabinet'),
		cabinet_counter('everycomp:rd/betternether/willow_cabinet_counter', 'everycomp:rd/betternether/willow_counter', 'everycomp:fd/betternether/willow_cabinet'),
		cabinet_counter('everycomp:rd/betternether/stalagnate_cabinet_counter', 'everycomp:rd/betternether/stalagnate_counter', 'everycomp:fd/betternether/stalagnate_cabinet'),
		cabinet_counter('everycomp:rd/betternether/wart_cabinet_counter', 'everycomp:rd/betternether/wart_counter', 'everycomp:fd/betternether/wart_cabinet'),
		cabinet_counter('everycomp:rd/betternether/nether_sakura_cabinet_counter', 'everycomp:rd/betternether/nether_sakura_counter', 'everycomp:fd/betternether/nether_sakura_cabinet'),
		cabinet_counter('everycomp:rd/betternether/rubeus_cabinet_counter', 'everycomp:rd/betternether/rubeus_counter', 'everycomp:fd/betternether/rubeus_cabinet'),
		cabinet_counter('everycomp:rd/betternether/mushroom_fir_cabinet_counter', 'everycomp:rd/betternether/mushroom_fir_counter', 'everycomp:fd/betternether/mushroom_fir_cabinet'),
		cabinet_counter('everycomp:rd/betternether/anchor_tree_cabinet_counter', 'everycomp:rd/betternether/anchor_tree_counter', 'everycomp:fd/betternether/anchor_tree_cabinet'),
		cabinet_counter('everycomp:rd/betterend/lucernia_cabinet_counter', 'everycomp:rd/betterend/lucernia_counter', 'everycomp:fd/betterend/lucernia_cabinet'),
		cabinet_counter('everycomp:rd/betterend/jellyshroom_cabinet_counter', 'everycomp:rd/betterend/jellyshroom_counter', 'everycomp:fd/betterend/jellyshroom_cabinet'),
		cabinet_counter('everycomp:rd/betterend/end_lotus_cabinet_counter', 'everycomp:rd/betterend/end_lotus_counter', 'everycomp:fd/betterend/end_lotus_cabinet'),
		cabinet_counter('everycomp:rd/betterend/umbrella_tree_cabinet_counter', 'everycomp:rd/betterend/umbrella_tree_counter', 'everycomp:fd/betterend/umbrella_tree_cabinet'),
		cabinet_counter('everycomp:rd/betterend/lacugrove_cabinet_counter', 'everycomp:rd/betterend/lacugrove_counter', 'everycomp:fd/betterend/lacugrove_cabinet'),
		cabinet_counter('everycomp:rd/betterend/helix_tree_cabinet_counter', 'everycomp:rd/betterend/helix_tree_counter', 'everycomp:fd/betterend/helix_tree_cabinet'),
		cabinet_counter('everycomp:rd/betterend/tenanea_cabinet_counter', 'everycomp:rd/betterend/tenanea_counter', 'everycomp:fd/betterend/tenanea_cabinet'),
		cabinet_counter('everycomp:rd/betterend/dragon_tree_cabinet_counter', 'everycomp:rd/betterend/dragon_tree_counter', 'everycomp:fd/betterend/dragon_tree_cabinet'),
		cabinet_counter('everycomp:rd/betterend/pythadendron_cabinet_counter', 'everycomp:rd/betterend/pythadendron_counter', 'everycomp:fd/betterend/pythadendron_cabinet'),
		cabinet_counter('everycomp:rd/betterend/mossy_glowshroom_cabinet_counter', 'everycomp:rd/betterend/mossy_glowshroom_counter', 'everycomp:fd/betterend/mossy_glowshroom_cabinet'),
		cabinet_counter('everycomp:rd/atmospheric/rosewood_cabinet_counter', 'everycomp:rd/atmospheric/rosewood_counter', 'abnormals_delight:rosewood_cabinet'),
		cabinet_counter('everycomp:rd/atmospheric/morado_cabinet_counter', 'everycomp:rd/atmospheric/morado_counter', 'abnormals_delight:morado_cabinet'),
		cabinet_counter('everycomp:rd/atmospheric/yucca_cabinet_counter', 'everycomp:rd/atmospheric/yucca_counter', 'abnormals_delight:yucca_cabinet'),
		cabinet_counter('everycomp:rd/atmospheric/aspen_cabinet_counter', 'everycomp:rd/atmospheric/aspen_counter', 'abnormals_delight:aspen_cabinet'),
		cabinet_counter('everycomp:rd/atmospheric/laurel_cabinet_counter', 'everycomp:rd/atmospheric/laurel_counter', 'abnormals_delight:laurel_cabinet'),
		cabinet_counter('everycomp:rd/atmospheric/kousa_cabinet_counter', 'everycomp:rd/atmospheric/kousa_counter', 'abnormals_delight:kousa_cabinet'),
		cabinet_counter('everycomp:rd/atmospheric/grimwood_cabinet_counter', 'everycomp:rd/atmospheric/grimwood_counter', 'abnormals_delight:grimwood_cabinet'),
		cabinet_counter('everycomp:rd/autumnity/maple_cabinet_counter', 'everycomp:rd/autumnity/maple_counter', 'abnormals_delight:maple_cabinet'),
		cabinet_counter('everycomp:rd/caverns_and_chasms/azalea_cabinet_counter', 'everycomp:rd/caverns_and_chasms/azalea_counter', 'abnormals_delight:azalea_cabinet'),
		cabinet_counter('everycomp:rd/environmental/willow_cabinet_counter', 'everycomp:rd/environmental/willow_counter', 'abnormals_delight:willow_cabinet'),
		cabinet_counter('everycomp:rd/environmental/pine_cabinet_counter', 'everycomp:rd/environmental/pine_counter', 'abnormals_delight:pine_cabinet'),
		cabinet_counter('everycomp:rd/environmental/plum_cabinet_counter', 'everycomp:rd/environmental/plum_counter', 'abnormals_delight:plum_cabinet'),
		cabinet_counter('everycomp:rd/environmental/wisteria_cabinet_counter', 'everycomp:rd/environmental/wisteria_counter', 'abnormals_delight:wisteria_cabinet'),

	    event.replaceInput(
	      { input: 'redeco:oak_cabinet' },
	      'redeco:oak_cabinet',           
	      'farmersdelight:oak_cabinet'    
	    ),
	    event.replaceInput(
	      { input: 'redeco:crimson_cabinet' },
	      'redeco:crimson_cabinet',           
	      'farmersdelight:crimson_cabinet'    
	    ),
	    event.replaceInput(
	      { input: 'redeco:warped_cabinet' },
	      'redeco:warped_cabinet',           
	      'farmersdelight:warped_cabinet'    
	    ),
	    event.replaceInput(
	      { input: 'redeco:mangrove_cabinet' },
	      'redeco:mangrove_cabinet',           
	      'farmersdelight:mangrove_cabinet'    
	    ),
	    event.replaceInput(
	      { input: 'redeco:cherry_cabinet' },
	      'redeco:cherry_cabinet',           
	      'farmersdelight:cherry_cabinet'    
	    ),
	    event.replaceInput(
	      { input: 'redeco:bamboo_cabinet' },
	      'redeco:bamboo_cabinet',           
	      'farmersdelight:bamboo_cabinet'    
	    ),
	    event.replaceInput(
	      { input: 'redeco:birch_cabinet' },
	      'redeco:birch_cabinet',           
	      'farmersdelight:birch_cabinet'    
	    ),
	    event.replaceInput(
	      { input: 'redeco:dark_oak_cabinet' },
	      'redeco:dark_oak_cabinet',           
	      'farmersdelight:dark_oak_cabinet'    
	    ),
	    event.replaceInput(
	      { input: 'redeco:acacia_cabinet' },
	      'redeco:acacia_cabinet',           
	      'farmersdelight:acacia_cabinet'    
	    ),
	    event.replaceInput(
	      { input: 'redeco:spruce_cabinet' },
	      'redeco:spruce_cabinet',           
	      'farmersdelight:spruce_cabinet'    
	    ),
	    event.replaceInput(
	      { input: 'redeco:jungle_cabinet' },
	      'redeco:jungle_cabinet',           
	      'farmersdelight:jungle_cabinet'    
	    )
	}
)
