
[general]
	disable_mod = false
	auto_start = false
	space_modules = false
	shadow_text = true
	animations = false
	animationSpeed = 1.0
	fontScale = 1.0
	background_color = 1867534416
	hide_debug_crosshair = false
	hide_sidebar = false
	hide_bossbar = false
	always_show_profiler = false
	always_show_tps = false

[[modules_left]]
	name = "chunks"
	name_color = 43775
	value_color = 16777045
	chunks_enabled_color = 5635925
	chunks_disabled_color = 16733525
	total_chunks_color = 16755200
	enabled = true

	[modules_left.lines]
		chunk_sections = false
		chunk_culling = false
		pending_chunks = false
		pending_uploads = false
		available_buffers = false
		client_chunk_cache = false
		loaded_chunks = true
		loaded_chunks_server = true
		forceloaded_chunks = false
		spawn_chunks = false
		chunk_file = false

[[modules_left]]
	name = "entity"
	name_color = 16733525
	value_color = 16777045
	total_entities_color = 16755200
	enabled = true

	[modules_left.lines]
		particles = true
		entities = true
		monster = true
		creature = true
		ambient = true
		axolotls = true
		underground_water_creature = true
		water_creature = true
		water_ambient = true
		misc = true
		wilderwildfireflies = false
		wilderwildjellyfish = false
		wilderwildcrab = false
		wilderwildtumbleweed = false
		cave_creature = false
		deep_sea_creature = false
		glares = true
		rascals = true

[[modules_left]]
	name = "fps"
	color_high = 5635925
	color_med = 16777045
	color_low = 16733525
	enabled = true

	[modules_left.lines]
		fps = true

[[modules_left]]
	name = "coords"
	name_color = 16733525
	color_x = 16733525
	color_y = 5635925
	color_z = 5636095
	enabled = true

	[modules_left.lines]
		player_coords = true
		block_coords = true
		chunk_relative_coords = true
		chunk_coords = true

[[modules_left]]
	name = "graphics"
	name_color = 16755200
	value_color = 5636095
	enabled = true

	[modules_left.lines]
		render_distance = true
		graphics = true
		clouds = true
		biome_blend_radius = false
		shader = true

[[modules_left]]
	name = "location"
	name_color = 43520
	value_color = 5636095
	enabled = true

	[modules_left.lines]
		dimension = true
		facing = false
		rotation = false
		light = false
		light_server = false
		highest_block = false
		highest_block_server = false
		biome = true
		local_difficulty = false
		day_ticks = false
		days_played = true
		slime_chunk = true

[[modules_right]]
	name = "help"
	name_color = 16645526
	value_color = 5636095
	enabled_color = 5635925
	disabled_color = 16733525
	enabled = true

	[modules_right.lines]
		pie_graph = true
		fps_tps = true
		help = true

[[modules_right]]
	name = "system"
	name_color = 16755200
	value_color = 5636095
	memory_color_toggle = true
	time_format = "HH:mm:ss"
	enabled = true

	[modules_right.lines]
		time = true
		java_version = true
		memory_usage = true
		allocation_rate = true
		allocated_memory = true
		cpu = true
		display = true
		gpu = true
		gpu_utilization = true
		opengl_version = true
		gpu_driver = true

[[modules_right]]
	name = "server"
	name_color = 11184810
	value_color = 16777045
	enabled = true

	[modules_right.lines]
		server_tick = true
		packets_sent = false
		packets_received = false

[[modules_right]]
	name = "sound"
	name_color = 16755200
	value_color = 5636095
	maximum_color = 43690
	enabled = true

	[modules_right.lines]
		sounds = true
		ambient_sounds = true
		mood = false

